name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Artifact name description
        required: true
        type: string
        default: dist
    outputs:
      result:
        description: The result of the successful deploy message
        value: ${{jobs.outputting-build-file.outputs.outcome}}

jobs:
  outputting-build-file:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Output contents
        run: ls
      - name: Outputting git hub output
        run: echo "$GITHUB_OUTPUT"
      - name: Workflow complete
        id: set-result
        run: echo "step-result=Workflow ran" >> $GITHUB_OUTPUT
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        run: echo 'Hello there'
